export const GET_DEALS_REQUEST = 'GET_DEALS_REQUEST';
export const GET_DEALS_SUCCESS = 'GET_DEALS_SUCCESS';
export const GET_DEALS_FAIL = 'GET_DEALS_FAIL';
export const GET_DEALS_RESET = 'GET_DEALS_RESET';

export const GET_PRODUCT_DETAILS_REQUEST = 'GET_PRODUCT_DETAILS_REQUEST';
export const GET_PRODUCT_DETAILS_SUCCESS = 'GET_PRODUCT_DETAILS_SUCCESS';
export const GET_PRODUCT_DETAILS_FAIL = 'GET_PRODUCT_DETAILS_FAIL';

export const GET_POPULAR_DEALS_REQUEST = 'GET_POPULAR_DEALS_REQUEST';
export const GET_POPULAR_DEALS_SUCCESS = 'GET_POPULAR_DEALS_SUCCESS';
export const GET_POPULAR_DEALS_FAIL = 'GET_POPULAR_DEALS_FAIL';

export const SEARCH_DEALS_REQUEST = 'SEARCH_DEALS_REQUEST';
export const SEARCH_DEALS_SUCCESS = 'SEARCH_DEALS_SUCCESS';
export const SEARCH_DEALS_FAIL = 'SEARCH_DEALS_FAIL';

export const GET_MORE_DEALS_REQUEST = 'GET_MORE_DEALS_REQUEST';
export const GET_MORE_DEALS_SUCCESS = 'GET_MORE_DEALS_SUCCESS';
export const GET_MORE_DEALS_FAIL = 'GET_MORE_DEALS_FAIL';
export const GET_MORE_DEALS_RESET = 'GET_MORE_DEALS_RESET';

export const CLEAR_ERROR = 'CLEAR_ERROR';
