export const GET_STORES_REQUEST = 'GET_STORES_REQUEST';
export const GET_STORES_SUCCESS = 'GET_STORES_SUCCESS';
export const GET_STORES_FAIL = 'GET_STORES_FAIL';



export const GET_STORE_DETAILS_REQUEST = 'GET_STORE_DETAILS_REQUEST';
export const GET_STORE_DETAILS_SUCCESS = 'GET_STORE_DETAILS_SUCCESS';
export const GET_STORE_DETAILS_FAIL = 'GET_STORE_DETAILS_FAIL';


export const CLEAR_ERROR = 'CLEAR_ERROR';